'use client';
import {useState,useEffect} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {topics,tips,makeQ,parseAnswer,type Q} from '@/lib/math';
type RecordItem={id:string;q:Q;answer:string;correct:boolean;date:string;seconds:number};
export default function Practice({signedIn}:{signedIn:boolean}){const [rows,setRows]=useState<RecordItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('practice'),[queue,setQueue]=useState<Q[]>([]),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[result,setResult]=useState<RecordItem|null>(null),[busy,setBusy]=useState(false),[started,setStarted]=useState(Date.now()),[attemptId,setAttemptId]=useState(''),[session,setSession]=useState<RecordItem[]>([]),[label,setLabel]=useState(''),[level,setLevel]=useState(1);
async function load(){setLoading(true);try{const r=await fetch('/api/attempts');const d:any=await r.json();if(!r.ok)throw Error(d.error);setRows(d.rows);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{if(signedIn)void load();else setLoading(false);},[signedIn]);
const stats=topics.map((_,t)=>{const recent=rows.filter(r=>r.q.topic===t).slice(0,20);return {n:recent.length,rate:recent.length?Math.round(recent.filter(r=>r.correct).length/recent.length*100):0};});
const recommended=stats.findIndex(s=>s.n<2)>=0?stats.findIndex(s=>s.n<2):stats.reduce((a,s,i)=>s.rate<stats[a].rate?i:a,0);
function begin(mode:string,topic=0,custom?:Q){const qs=custom?[{...custom,id:crypto.randomUUID()}]:mode==='测评'?Array.from({length:12},(_,i)=>makeQ(i%6,1)):Array.from({length:8},()=>makeQ(topic,level));setQueue(qs);setIndex(0);setAnswer('');setResult(null);setStarted(Date.now());setAttemptId(crypto.randomUUID());setSession([]);setLabel(custom?'错题重练':mode==='测评'?'基础测评':topics[topic]);setTab('practice');setError('');}
async function submit(e:React.FormEvent){e.preventDefault();if(busy||result)return;if(parseAnswer(answer)===null){setError('请输入数字或分数，例如 -3、0.5、3/4。');return;}setBusy(true);setError('');try{const r=await fetch('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:attemptId,q:queue[index],answer,seconds:Math.round((Date.now()-started)/1000)})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setResult(d);setRows(prev=>prev.some(x=>x.id===d.id)?prev:[d,...prev]);setSession(prev=>[...prev,d]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
function next(){setIndex(index+1);setAnswer('');setResult(null);setStarted(Date.now());setAttemptId(crypto.randomUUID());}
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'read_math_progress',description:'读取当前页面已加载的六项数学运算练习统计。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!input||Object.keys(input).length)throw Error('不接受参数');return{loaded:!loading,total:rows.length,topics:stats.map((s,i)=>({name:topics[i],...s}))};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[rows,loading]);
const mistakes=rows.filter(r=>!r.correct).filter((r,i,a)=>a.findIndex(x=>x.q.text===r.q.text)===i);const total=rows.length,correct=rows.filter(r=>r.correct).length;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'});const todayCount=rows.filter(r=>today.format(new Date(r.date))===today.format(new Date())).length;
return <div className="shell"><header><div className="brand"><span className="logo">÷</span><strong>运算练习室</strong><span className="edition">人教版 · 七年级上册</span></div><span className="account">{signedIn?'学习记录已关联当前账号':'登录后保存记录'}</span></header><main><div className="heading"><div><p className="eyebrow">每天一点，算得更稳</p><h1>今天，练好一项运算。</h1><p className="muted">先找到容易出错的地方，再有针对性地练习。</p></div><div className="today"><span>今日已完成</span><strong>{todayCount}<small> 题</small></strong></div></div><div className="metrics"><div><span>累计练习</span><strong>{total}<small>题</small></strong></div><div><span>整体正确率</span><strong>{total?Math.round(correct/total*100):'—'}<small>{total?'%':''}</small></strong></div><div><span>错题待复习</span><strong>{mistakes.filter(m=>!rows.some(r=>r.correct&&r.q.text===m.q.text&&r.date>m.date)).length}<small>题</small></strong></div></div>
{!signedIn&&<div className="notice">登录后即可开始练习，并保存答题记录。<a href="/signin-with-chatgpt?return_to=%2F" target="_top">登录并继续</a></div>}{error&&<div role="alert" className="error">{error} {!queue.length&&signedIn&&<button onClick={load}>重新读取</button>}</div>}
<Tabs value={tab} onValueChange={setTab}><TabsList className="nav"><TabsTrigger value="practice">开始练习</TabsTrigger><TabsTrigger value="mistakes">错题本</TabsTrigger><TabsTrigger value="history">学习记录</TabsTrigger></TabsList><TabsContent value="practice"><div className="workspace"><section className="primary">
{!queue.length?<><div className="sectionline"><span className="badge">推荐练习</span><span className="muted">8 题 / 次</span></div><h2>{topics[recommended]}</h2><p className="muted">{loading?'正在读取学习记录…':stats[recommended].n<2?'这一项还没有足够的练习记录，先试一组看看。':`最近 ${stats[recommended].n} 题正确率 ${stats[recommended].rate}%，建议再练一组。`}</p><div className="rule"><span>解题提醒</span><p>{tips[recommended]}</p></div><div className="actions"><button className="blue" disabled={!signedIn||loading} onClick={()=>begin('专项',recommended)}>开始推荐练习</button><button disabled={!signedIn||loading} onClick={()=>begin('测评')}>做 12 题基础测评</button></div><p className="footnote">测评覆盖六个专项，用来安排后续练习。</p></>:index>=queue.length?<><span className="badge">本次练习完成</span><h2>又稳了一点。</h2><div className="score">{session.filter(r=>r.correct).length}<small> / {queue.length} 题正确</small></div><p className="muted">{session.every(r=>r.correct)?'全部答对！可以尝试进阶练习。':'错题已记录，建议先查看步骤，再重新做一遍。'}</p><div className="actions"><button className="blue" onClick={()=>setQueue([])}>返回练习首页</button><button onClick={()=>{setQueue([]);setTab('mistakes');}}>查看错题</button></div></>:<><div className="sectionline"><span className="badge">{label}</span><span>第 {index+1} / {queue.length} 题</span></div><Progress value={index/queue.length*100}/><p className="muted questionhint">{queue[index].topic===5?'解方程，求 x 的值':'计算下式，填写结果'}</p><div className="question">{queue[index].text}</div><form onSubmit={submit}><label htmlFor="answer">你的答案</label><div className="answerline"><input autoFocus id="answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="支持负数、小数和分数" disabled={!!result||busy} autoComplete="off"/><button className="blue" disabled={busy||!!result}>{busy?'保存中…':'提交答案'}</button></div></form>{result&&<div aria-live="polite" className={'feedback '+(result.correct?'good':'wrong')}><strong>{result.correct?'答对了':'这题需要再看一下'} · 正确答案：{queue[index].answer}</strong><ol>{queue[index].steps.map((s,i)=><li key={i}>{s}</li>)}</ol><button className="blue" onClick={next}>{index+1===queue.length?'查看练习结果':'下一题'}</button></div>}<p className="footnote">答题后自动保存。若暂时退出，已完成的题目仍保留在学习记录中。</p><button className="textbutton" onClick={()=>setQueue([])}>结束本次练习</button></>}
</section><aside className="diagnosis"><h3>我的运算画像</h3><p className="muted">每项最近 20 题的正确率</p>{stats.map((s,i)=><div className="ability" key={i}><div><span>{topics[i]}</span><b>{s.n?`${s.rate}%`:'未测'}</b></div><Progress value={s.rate}/><small>{s.n?`${s.n} 题记录`:'完成练习后显示'}</small></div>)}</aside></div><section className="topics"><div className="sectionline"><h3>按专项练习</h3><div className="difficulty"><span>难度</span><button aria-pressed={level===1} onClick={()=>setLevel(1)}>基础</button><button aria-pressed={level===2} onClick={()=>setLevel(2)}>进阶</button></div></div><div className="topicgrid">{topics.map((t,i)=><button className="topic" disabled={!signedIn||loading} key={t} onClick={()=>begin('专项',i)}><span className="number">0{i+1}</span><strong>{t}</strong><span>{tips[i]}</span></button>)}</div></section></TabsContent>
<TabsContent value="mistakes"><section className="panel"><h2>错题本</h2><p className="muted">重新做对后标记为已订正；旧记录仍保留。</p>{!mistakes.length?<div className="empty">{loading?'正在读取…':'还没有错题。完成一组练习后，有需要复习的题目会出现在这里。'}</div>:mistakes.map(m=>{const fixed=rows.some(r=>r.correct&&r.q.text===m.q.text&&r.date>m.date);return <article className="record" key={m.id}><div className="sectionline"><span className="badge">{topics[m.q.topic]}</span><span>{fixed?'已订正':'待复习'}</span></div><h3>{m.q.text}</h3><p>上次答案：{m.answer} · 正确答案：{m.q.answer}</p><details><summary>查看解题步骤</summary><ol>{m.q.steps.map((s,i)=><li key={i}>{s}</li>)}</ol></details><button disabled={!signedIn} onClick={()=>begin('专项',m.q.topic,m.q)}>重新做这题</button></article>;})}</section></TabsContent>
<TabsContent value="history"><section className="panel"><h2>学习记录</h2><p className="muted">显示最近 3000 次答题，时间按北京时间显示。</p>{!rows.length?<div className="empty">{loading?'正在读取…':'还没有练习记录，先从基础测评开始吧。'}</div>:rows.map(r=><article className="historyrow" key={r.id}><span className={r.correct?'statusgood':'statusbad'}>{r.correct?'正确':'错误'}</span><div><strong>{r.q.text}</strong><p>{topics[r.q.topic]} · 你的答案 {r.answer} · 用时 {r.seconds} 秒</p></div><time>{new Date(r.date).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></article>)}</section></TabsContent></Tabs><footer>练习范围：人教版七年级上册运算基础 · 学习记录随当前登录账号保存</footer></main></div>;
}
